### PR TITLE
feat: localization support and spanish translation

### PR DESCRIPTION
**Pull request by SrIzan10**
- removed some unused code
- saves selected language to localStorage
- complete spanish translation

### CODE REVIEW

**Review by Murtatrxx — COMMENTED** [review]
Looks fine, I'll add tr as soon as possible

**Comment by SrIzan10** [comment]
nice ty!

**Review by jacoobes — APPROVED** [review]
lgtm

**Comment by SrIzan10** [comment]
@Murtatrxx do you need any help on translating gui to tr?

**Comment by Murtatrxx** [comment]
How many sentences are there approx?

**Comment by SrIzan10** [comment]
about 18

**Pull request merged**
